"""Add default_price to LensType

Revision ID: 11f2440bff51
Revises: ad2fa441693a
Create Date: 2025-06-05 14:18:02.294045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11f2440bff51'
down_revision = 'ad2fa441693a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lens_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lens_types', schema=None) as batch_op:
        batch_op.drop_column('default_price')

    # ### end Alembic commands ###
