"""update customer email unique constraint

Revision ID: 1716303e4d21
Revises: 2b760085f62f
Create Date: 2025-06-05 15:00:23.101785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1716303e4d21'
down_revision = '2b760085f62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index('ix_customers_email_unique', ['email'], unique=True, postgresql_where=sa.text("email != ''"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index('ix_customers_email_unique', postgresql_where=sa.text("email != ''"))

    # ### end Alembic commands ###
