"""Add default_price to LensCutType

Revision ID: 2b760085f62f
Revises: 11f2440bff51
Create Date: 2025-06-05 14:22:42.387264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b760085f62f'
down_revision = '11f2440bff51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lens_cut_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_price', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lens_cut_types', schema=None) as batch_op:
        batch_op.drop_column('default_price')

    # ### end Alembic commands ###
