"""Remove delivery_date from orders

Revision ID: aa71e9dcda4d
Revises: addchatid20240605
Create Date: 2025-06-05 18:22:16.765489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa71e9dcda4d'
down_revision = 'addchatid20240605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_date', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
